---
version: "3"

tasks:
  default:
    silent: true
    cmd: task -l

  gen-proto:
    desc: "Generate proto source"
    cmd: protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/go-hello.proto
