---
version: "3"

tasks:
    default:
        silent: true
        cmd: task -l

    fmt:
        desc: "Format source files"
        cmd: nix fmt

    lint:
        desc: "Lint source files"
        cmd: golangci-lint run
