// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: proto/go-hello.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoHello_IsHealthy_FullMethodName = "/proto.GoHello/IsHealthy"
)

// GoHelloClient is the client API for GoHello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoHelloClient interface {
	IsHealthy(ctx context.Context, in *IsHealthyRequest, opts ...grpc.CallOption) (*IsHealthyResponse, error)
}

type goHelloClient struct {
	cc grpc.ClientConnInterface
}

func NewGoHelloClient(cc grpc.ClientConnInterface) GoHelloClient {
	return &goHelloClient{cc}
}

func (c *goHelloClient) IsHealthy(ctx context.Context, in *IsHealthyRequest, opts ...grpc.CallOption) (*IsHealthyResponse, error) {
	out := new(IsHealthyResponse)
	err := c.cc.Invoke(ctx, GoHello_IsHealthy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoHelloServer is the server API for GoHello service.
// All implementations must embed UnimplementedGoHelloServer
// for forward compatibility
type GoHelloServer interface {
	IsHealthy(context.Context, *IsHealthyRequest) (*IsHealthyResponse, error)
	mustEmbedUnimplementedGoHelloServer()
}

// UnimplementedGoHelloServer must be embedded to have forward compatible implementations.
type UnimplementedGoHelloServer struct {
}

func (UnimplementedGoHelloServer) IsHealthy(context.Context, *IsHealthyRequest) (*IsHealthyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsHealthy not implemented")
}
func (UnimplementedGoHelloServer) mustEmbedUnimplementedGoHelloServer() {}

// UnsafeGoHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoHelloServer will
// result in compilation errors.
type UnsafeGoHelloServer interface {
	mustEmbedUnimplementedGoHelloServer()
}

func RegisterGoHelloServer(s grpc.ServiceRegistrar, srv GoHelloServer) {
	s.RegisterService(&GoHello_ServiceDesc, srv)
}

func _GoHello_IsHealthy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsHealthyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoHelloServer).IsHealthy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoHello_IsHealthy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoHelloServer).IsHealthy(ctx, req.(*IsHealthyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoHello_ServiceDesc is the grpc.ServiceDesc for GoHello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoHello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GoHello",
	HandlerType: (*GoHelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsHealthy",
			Handler:    _GoHello_IsHealthy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/go-hello.proto",
}
